/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n5.1-27-g6f53f0d09e-20220831"
#endif /* AVUTIL_FFVERSION_H */
